### ISSUE TITLE
 useless as a 'native' mobile app?

### ISSUE THREAD

**Issue by mubiesam** [Pjaerr/PWA-Timer#1]
@Pjaerr Sorry for my bad English, but not sure what to choose after reading this...
"Due to restrictions on mobile devices, the timer cannot continue counting in real time when in the background, so it is rendered sort of useless as a 'native' mobile app, but the concept of PWAs stays the same."

So if I really need to use timer as a reminder, better to write the native app? or there is workaround to stay with PWA?

Thanks,

**Comment by Pjaerr** [comment]
@mubiesam I think for an app like this where the timer needs to count in the background, it doesn't work well as a PWA (Unless things have changed and it is possible now). It works in the background on desktop because the timer process is in a different thread (background worker) but mobile still throttles this.

**Comment by Pjaerr** [comment]
@mubiesam It was a while ago I looked into this stuff, but I think you might be able to ping the service worker to keep the process alive in the background but I'm still unsure. It's worth looking up JavaScript background processes (where you send messages between threads) and see if mobile keeps them alive now.

**Comment by mubiesam** [comment]
@Pjaerr Thank you for the quick response. 
Is web workers capable of doing the job as you mentioned...
https://www.w3schools.com/html/html5_webworkers.asp
https://www.codeproject.com/Tips/1141206/Developing-a-Background-Task-in-Less-than-Minutes

**Comment by Pjaerr** [comment]
@mubiesam The application is using a web worker to ensure that it keeps running when the tab isn't focused, this still didn't work on mobile.

**Comment by Pjaerr** [comment]
@mubiesam In my application I only used service workers to cache the page for offline use and then I used web workers for the timer in the background as keeping it in the main thread stopped it working on desktop too. You can, however, use a service worker to carry out background tasks on mobile too (which i haven't looked into much). I'm not sure if you can run a timer that pings every second though because maybe chrome would throttle it. It is worth trying out, if I get some free time I will try this out and let you know. If you try it out, let me know :D

https://developers.google.com/web/fundamentals/primers/service-workers/

**Comment by Pjaerr** [comment]
@mubiesam I tested the app on mobile (to see if anything has changed since I made it) and it stops working in the background after 12:30 minutes

**Comment by mubiesam** [comment]
@Pjaerr Thanks for the update.
Is it possible to use functional events such as push and sync to reset the timer?
https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle

**Comment by Pjaerr** [comment]
@mubiesam I don't know if they'd work for something like a timer, I haven't used them before so I could be wrong.

**Comment by mubiesam** [comment]
@Pjaerr Thanks for your help, I will get back to you if I find something.

**Comment by justingolden21** [comment]
Man I really wish PWAs could have working timers / alarms on mobile.

You could have a stopwatch by remembering the UTC time when it started and then calculating the difference when it stops after reopening the app.

But I think the best you can do on mobile for an alarm would be a notification, or playing a sound only if the app is open.

Let me know if these assumptions are still correct or if there's any new info on this...
